### ISSUE TITLE
Full speed mode

### ISSUE THREAD

**Issue by Nolaan** [mczerski/SD-card-controller#2]
Hi,
Can you tell me if the controller is operating at full speed in SD mode?

**Comment by mczerski** [comment]
controller supports default and high speed modes. to support default mode controller have to be clocked at f >= 50MHz, tu support high speed mode f >= 100MHz. With a little bit of coding this can be reduced down to 25MHz and 50 MHz respectively.

**Comment by Nolaan** [comment]
Thank you very much Marek!
